import Head from 'next/head'
import Image from 'next/image'
import { Inter } from 'next/font/google'
// import styles from 'src/styles/Home.module.css'
import Button from '@components/Button'
import { useEffect, useRef, useState } from 'react'
import { css } from '@emotion/react'

const inter = Inter({ subsets: ['latin'] })

export default function Home() {
  // const [products, setProducts] = useState<
  //   { id: string; properties: { id: string }[] }[]
  // >([])
  const [products, setProducts] = useState<
    { id: string; name: string; createdAt: string }[]
  >([])
  // useEffect(() => {
  //   fetch('api/get-items')
  //     .then((res) => res.json())
  //     .then((data) => setProducts(data.items))
  // }, [])
  useEffect(() => {
    fetch('api/get-products')
      .then((res) => res.json())
      .then((data) => setProducts(data.items))
  }, [])
  const inputRef = useRef<HTMLInputElement>(null)
  const handleClick = () => {
    if (inputRef.current == null || inputRef.current.value === '') {
      alert('name을 넣어주세요')
      return
    }
    fetch(`api/add-item?name=${inputRef.current.value}`)
      .then((res) => res.json())
      .then((data) => alert(data.message))
  }
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <div>
          <input
            className="placeholder:italic placeholder:text-slate-400 block bg-white w-96 border border-slate-300 rounded-md py-2 pl-2 pr-3 shadow-sm focus:outline-none focus:border-sky-500 focus:ring-sky-500 focus:ring-1 sm:text-sm"
            type="text"
            ref={inputRef}
            placeholder="name"
          />
          <button
            css={css`
              background-color: hotpink;
              padding: 16px;
              border-radius: 8px;
            `}
            onClick={handleClick}
          >
            Add Jacket
          </button>

          <Button onClick={handleClick}>Button2</Button>
          <div>
            <p>Product List</p>
            {/* {products &&
              products.map((item) => (
                <div key={item.id}>
                  {JSON.stringify(item)}
                  {item.properties &&
                    Object.entries(item.properties).map(([key, value]) => (
                      <button
                        key={key}
                        onClick={() => {
                          fetch(
                            `api/get-detail?pageId=${item.id}&propertyId=${value.id}`
                          ).then((res) =>
                            res
                              .json()
                              .then((data) =>
                                alert(JSON.stringify(data.detail))
                              )
                          )
                        }}
                      >
                        {key}
                      </button>
                    ))}
                  <br />
                  <br />
                </div>
              ))} */}
            {products &&
              products.map((item) => (
                <div key={item.id}>
                  {item.name}
                  <span>{item.createdAt}</span>
                </div>
              ))}
          </div>
        </div>
      </main>
    </>
  )
}
